\getenv app_password POSTGRES_APP_PASSWORD
CREATE ROLE wagering_app LOGIN PASSWORD :'app_password';
GRANT CONNECT ON DATABASE wagering TO wagering_app;
GRANT USAGE ON SCHEMA public TO wagering_app;
ALTER DEFAULT PRIVILEGES FOR ROLE wagering IN SCHEMA public GRANT SELECT,INSERT,UPDATE ON TABLES TO wagering_app;
ALTER DEFAULT PRIVILEGES FOR ROLE wagering IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO wagering_app;
