ALTER TABLE wallet_ledger_entries DROP CONSTRAINT ledger_seq_unique;
ALTER TABLE wager_transactions DROP CONSTRAINT attempts_nonnegative;
ALTER TABLE inbox_messages DROP COLUMN deliveries;
DROP TRIGGER outbox_immutable ON outbox_events;
DROP FUNCTION guard_outbox();
DROP TRIGGER ledger_tx_integrity ON wallet_ledger_entries;
DROP TRIGGER tx_integrity ON wager_transactions;
DROP FUNCTION check_transaction_integrity();
DROP TRIGGER ledger_wallet_integrity ON wallet_ledger_entries;
DROP TRIGGER wallet_integrity ON wallets;
DROP FUNCTION check_wallet_integrity();
DROP TRIGGER ledger_append ON wallet_ledger_entries;
DROP FUNCTION guard_ledger_append();
DROP TRIGGER transaction_guard ON wager_transactions;
DROP FUNCTION guard_transaction();
DROP TRIGGER wallet_guard ON wallets;
DROP FUNCTION guard_wallet();
DROP INDEX uq_tx_one_reversal;
DROP INDEX ix_ledger_wallet_seq;
DROP INDEX ix_outbox_transaction;
ALTER TABLE wallets DROP CONSTRAINT supported_currency;
ALTER TABLE wager_transactions DROP CONSTRAINT supported_currency, DROP CONSTRAINT internal_shape, DROP CONSTRAINT waiting_shape, DROP CONSTRAINT state_shape, DROP CONSTRAINT amount_policy, DROP COLUMN correlation_id, DROP COLUMN causation_id;
