BEGIN;
DROP FUNCTION accounting_reverse_settlement(UUID,TIMESTAMPTZ);
DROP FUNCTION accounting_execute_settlement(UUID,TIMESTAMPTZ);
DROP FUNCTION accounting_opening_entry(UUID,UUID,TIMESTAMPTZ);
DROP FUNCTION accounting_consume(UUID,UUID,BIGINT,TIMESTAMPTZ);
DROP FUNCTION accounting_move(UUID,UUID,UUID,BIGINT,UUID,TIMESTAMPTZ);
DROP FUNCTION accounting_post(UUID,UUID,TEXT,BIGINT,TIMESTAMPTZ);
DROP FUNCTION accounting_emit(UUID,TEXT,TIMESTAMPTZ);
COMMIT;
